allow max 4GB files to be created on 32bit machine
AppImageCommunity/libappimage pull request #189
Opened 2023-09-16 12:14 UTC by hyh19962008

appimagetool will crash on appimage_get_elf_section_offset_and_length() when creating file larger than 2GB on 32bit machine, because in this line lssek() returns -1 and errno set to EOVERFLOW:
```c
size_t map_size = (size_t) lseek(fd, 0, SEEK_END);
```
Adding "#define _FILE_OFFSET_BITS 64" will change off_t to 64bit, then we can get the correct file size from lseek. Unfortunately, map_size still have to use size_t (aka uint32_t), this limits the max created file to 4GB. As a matter of fact, the ELF specification also limits the max file size to 4GB. So, 4GB is the best we can get.

related issues:
#21 
> https://github.com/AppImage/AppImageKit/issues/1181

2023-09-16 17:41 UTC, hyh19962008 commented
I was able to create files larger than 4GB now

2023-10-20 10:12 UTC, hyh19962008 commented
I made a build for testing, it only works well on native 32bit system. Running it on a 64bit system still gets the same problem.
[appimagetool-i686-4GBpatched.appimage](https://www.mediafire.com/file/ti1oagch2mm7rre/appimagetool-i686-4GBpatched.appimage/file)

2024-11-25 04:08 UTC, TheAssassin commented on src/libappimage_shared/elf.c
> +		map_size = (size_t)file_size;
We could just always use `UINT_MAX`, couldn't we?

2024-11-26 03:32 UTC, TheAssassin requested changes
Thanks for your contribution. However, it doesn't work the way you think. I'll open my own version soon.

2024-11-26 03:32 UTC, TheAssassin commented on src/libappimage_shared/elf.c
> +#define _FILE_OFFSET_BITS 64
While doing some research on the topic anyway for zsync2/AppImageUpdate (which use libgpgme which in turn uses 64-bit types for file sizes apparently), I found that this is not the right way. You should set it as a compiler definition. Then, you can skip the detection logic and `mmap`/`open` work as expected.

In theory, we could also just hardcode `UINT_MAX`...

2024-11-26 03:33 UTC, closed without merging